tensor(텐서) : 파이토치에서 다양한 수식을 계산하는데 사용되는 기본적 자료구조(행렬, 벡터구조)

차원 0 : 숫자 1개 => 스칼라

차원 1 : 벡터

차원 2 : 행렬

차원 3이상 : N차원 Tensor

In [2]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])     # 3x3 텐서 선언
print(x)

print("Size ", x.size())
print("Shape ", x.shape)
print("랭크(차원) ", x.ndimension())


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size  torch.Size([3, 3])
Shape  torch.Size([3, 3])
랭크(차원)  2


In [5]:
x = torch.unsqueeze(x, 0) #텐서 차원 늘리기
print(x)
print("Size ", x.size())
print("Shape ", x.shape)
print("랭크(차원) ", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size  torch.Size([1, 3, 3])
Shape  torch.Size([1, 3, 3])
랭크(차원)  3


In [6]:
x = torch.squeeze(x) #크기가 1인 차원들을 삭제하여 차원 줄이기
print(x)
print("Size ", x.size())
print("Shape ", x.shape)
print("랭크(차원) ", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size  torch.Size([3, 3])
Shape  torch.Size([3, 3])
랭크(차원)  2


In [7]:
x = x.view(9)       #view를 이용해 직접 모양 변경하기
print(x)
print("Size ", x.size())
print("Shape ", x.shape)
print("랭크(차원) ", x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size  torch.Size([9])
Shape  torch.Size([9])
랭크(차원)  1


In [9]:
#텐서간의 행렬 곱
w = torch.randn(5,3, dtype = torch.float)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
print("w size ", w.size())
print("x Size", x.size())
print('w : ', w)
print('x : ', x)

w size  torch.Size([5, 3])
x Size torch.Size([3, 2])
w :  tensor([[-0.2550,  0.5773,  0.0249],
        [ 0.3048, -0.5923,  0.3582],
        [ 1.2129, -1.2982,  0.1708],
        [-1.7905,  0.0952, -0.5701],
        [ 0.8299, -0.9441, -0.4282]])
x :  tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [10]:
b = torch.randn(5,2, dtype = torch.float)
print("b Size", b.size())
print('b : ', b)

b Size torch.Size([5, 2])
b :  tensor([[-1.8252, -0.2621],
        [-1.3364,  0.9422],
        [-0.5692,  1.7633],
        [-0.5530, -0.5614],
        [ 0.0945, -0.4804]])


In [11]:
wx = torch.mm(w, x) #행렬곱
print("wx size: ", wx.size())
print("wx : ", wx)

wx size:  torch.Size([5, 2])
wx :  tensor([[ 1.6014,  1.9485],
        [ 0.3189,  0.3896],
        [-1.8277, -1.7422],
        [-4.3552, -6.6206],
        [-4.1433, -4.6857]])


In [12]:
result = wx + b
print("result size: ", result.size())
print("result : ", result)

result size:  torch.Size([5, 2])
result :  tensor([[-0.2238,  1.6864],
        [-1.0175,  1.3318],
        [-2.3969,  0.0212],
        [-4.9082, -7.1819],
        [-4.0488, -5.1661]])
